#!/bin/bash
#SBATCH --ntasks=1
#SBATCH --time=12:00:00
#SBATCH --cpus-per-task=8
#SBATCH --mem-per-cpu=8G

####################################################################################################
# Specify the following variables with absolute paths for software, Staridx path, Gtf.
####################################################################################################
# ScriptPath:   path to software (e.g., /bin/)
# StaridxPath:  path to genomic index generated by STAR mapping (e.g., /ref/staridx/starhg38mask14add)
####################################################################################################
ScriptPath=/pipeline/bin
StaridxPath=/labshare/staridx/starmm10mask16add/
####################################################################################################

function mapping() {
    mkdir $WorkPath/$Outprefix/mapping
    cd $WorkPath/$Outprefix/mapping

    ## STAR mapping
    $ScriptPath/STAR-2.7.1a/bin/Linux_x86_64/STAR \
    --runThreadN 8 \
    --runMode alignReads \
    --readFilesCommand zcat \
    --genomeDir $StaridxPath \
    --readFilesIn $Fastq_R1 $Fastq_R2 \
    --outFileNamePrefix $Outprefix_ \
    --genomeLoad NoSharedMemory \
    --outReadsUnmapped Fastx \
    --outFilterMultimapNmax 10 \
    --outFilterScoreMinOverLread 0.66 \
    --outSAMattributes All \
    --outSAMtype BAM SortedByCoordinate \
    --alignIntronMin 21 \
    --scoreGenomicLengthLog2scale -1
    }

####################################################################################################

####################################################################################################
# Specify the following variables with absolute paths for software, Staridx path, Gtf.
####################################################################################################
# WorkPath:     path for writing output files  (e.g., /data/mapping/test)
# Fastq:        fastq file(s) to map (e.g., /preprocessing/test/x.fastq)
# Outprefix:    prefix for output file names, typically the barcode or sample name "R701" (e.g., test)
####################################################################################################

WorkPath=/
Fastq_R1=R1.fastq.gz
Fastq_R2=R2.fastq.gz
Outprefix=WT_CR_1
mapping;